#if !defined(AFX_GDIPLUSPLOT_H__900E791F_268C_4E74_9EC3_F5334416881B__INCLUDED_)
#define AFX_GDIPLUSPLOT_H__900E791F_268C_4E74_9EC3_F5334416881B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGDIPlusPlot wrapper class

class CGDIPlusPlot : public CWnd
{
protected:
	DECLARE_DYNCREATE(CGDIPlusPlot)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xdcd24674, 0xd4a1, 0x4ece, { 0xb6, 0xa0, 0xd8, 0x54, 0xdb, 0x5a, 0xd6, 0x92 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetCaption();
	void SetCaption(LPCTSTR);
	BOOL GetXTime();
	void SetXTime(BOOL);
	CString GetXLabel();
	void SetXLabel(LPCTSTR);
	CString GetYLabel();
	void SetYLabel(LPCTSTR);
	short GetInterval();
	void SetInterval(short);
	CString GetAnnolabel();
	void SetAnnolabel(LPCTSTR);
	BOOL GetXTrack();
	void SetXTrack(BOOL);

// Operations
public:
	void PlotXY(double xValue, double yValue, short index);
	void SetRange(double xMin, double xMax, double yMin, double yMax);
	void PlotY(double newValue, short index);
	void ClearGraph();
	void AddElement(short color);
	void IsElementVisible(short index, BOOL visible);
	void SetXCursorPos(double xValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GDIPLUSPLOT_H__900E791F_268C_4E74_9EC3_F5334416881B__INCLUDED_)
